import { BlogItem, Container } from "@/components/shared";
import { cn } from "@/lib/utils";
import { prisma } from "@/prisma/prisma-client";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Next Blog | Публічні блоги",
  description: "Generated by create next app",
};

export const revalidate = 60;

export default async function BlogsPage() {
  const blogs = await prisma.blog.findMany({
    where: { status: "PUBLIC" },
    include: { user: { select: { fullName: true, username: true } } },
  });
  return (
    <Container>
      <h1 className="text-3xl font-bold mb-5">Публічні блоги</h1>
      <div className="grid grid-cols-[repeat(2,_50%)] gap-[30px]">
        {blogs.map((blog, index) => (
          <Link
            className={cn("animate")}
            style={{ animationDelay: `${0.06 * (index + 1)}s` }}
            key={blog.id}
            href={`/blogs/${blog.username}`}
          >
            <BlogItem
              fullName={blog.user.fullName}
              title={blog.title}
              description={blog.description}
              tag={blog.status}
            />
          </Link>
        ))}
      </div>
    </Container>
  );
}
