import { SideNav } from "@/components/shared";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Next Blog | Мій блог",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <main>
      <SideNav />
      {modal}
      {children}
    </main>
  );
}
